version: '3.3'

services:

  wordpress:
#    image: wordpress:4-php7.1-fpm-alpine
    image: teknakat/ttkirja
    volumes:
      - type: volume
        source: ttkirja-webroot-stage
        target: /var/www/html
        volume:
          nocopy: true
    networks:
      - proxy
      - mariadb
    environment:
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/ttkirja_mysql_pwd
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_NAME: wp4ttkirja
    secrets:
      - ttkirja_mysql_pwd
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=ttkirjatest.tek.fi
        - com.df.port=8005
        - com.df.httpsOnly=true
        - com.df.redirectFromDomain=teekkarintyokirja.fi,www.teekkarintyokirja.fi
      placement:
        constraints: [node.hostname == dcatest]

networks:
  proxy:
    external: true
  mariadb:
    external: true

volumes:
  ttkirja-webroot-stage:
    external: true

secrets:
  ttkirja_mysql_pwd:
    file: /srv/docker/secrets/ttkirja_mysql_pwd
