version: '3.3'

services:

  wordpress:
    image: teknakat/ttkirja
    volumes:
      - type: volume
#        source: ttkirja-webroot
        source: ttkirja-webroot-stage
        target: /usr/src/wordpress
        volume:
          nocopy: true
    networks:
      - proxy
      - mariadb
    environment:
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/ttkirja_mysql_pwd
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wp4ttkirja
      WORDPRESS_DB_NAME: wp4ttkirja
    secrets:
      - ttkirja_mysql_pwd
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=ttkirjatest.tek.fi
#        - com.df.serviceDomain=teekkarintyokirja.tek.fi
        - com.df.port=8005
        - com.df.httpsOnly=false
#        - com.df.redirectFromDomain=teekkarintyokirja.fi,www.teekkarintyokirja.fi
      placement:
#        constraints: [node.hostname == dca.tek.fi]
        constraints: [node.hostname == dcatest]

networks:
  proxy:
    external: true
  mariadb:
    external: true

volumes:
  ttkirja-webroot-stage:
#  ttkirja-webroot:
    external: true

secrets:
  ttkirja_mysql_pwd:
    file: /srv/docker/secrets/ttkirja_mysql_pwd
